##Branching with `if`, `else` and `elif`

In [1]:
a_number = 34

In [2]:
if a_number % 2 == 0:
    print("We're inside an if block")
    print('The given number {} is even.'.format(a_number))

We're inside an if block
The given number 34 is even.

### The `else` statement

In [3]:
a_number = 33

In [4]:
if a_number % 2 == 0:
    print('The given number {} is even.'.format(a_number))
else:
    print('The given number {} is odd.'.format(a_number))

The given number 33 is odd.

Here's another example, which uses the `in` operator to check membership within a tuple.

In [5]:
the_3_musketeers = ('Athos', 'Porthos', 'Aramis')

In [7]:
a_candidate = "XYZ"

In [8]:
if a_candidate in the_3_musketeers:
    print("{} is a musketeer".format(a_candidate))
else:
    print("{} is not a musketeer".format(a_candidate))

XYZ is not a musketeer

### The `elif` statement

Python also provides an `elif` statement (short for "else if") to chain a series of conditional blocks. The conditions are evaluated one by one. For the first condition that evaluates to `True`, the block of statements below it is executed. The remaining conditions and statements are not evaluated. So, in an `if`, `elif`, `elif`... chain, at most one block of statements is executed, the one corresponding to the first condition that evaluates to `True`.

In [9]:
today = 'Wednesday'

In [10]:
if today == 'Sunday':
    print("Today is the day of the sun")
elif today == 'Monday':
    print("Today is the day of the moon")
elif today == 'Tuesday':
    print("Today is the day of Tyr")
elif today == 'Wednesday':
    print("Today is the day of Odin")
elif today == 'Thursday':
    print("Today is the day of Thor")
elif today == 'Friday':
    print("Today is the day of Frigga.")
elif today == 'Saturday':
    print("Today is the day of Saturn")

Today is the day of Odin

In the above example, the first 3 conditions evaluate to `False`, so none of the first 3 messages are printed. The fourth condition evaluates to `True`, so the corresponding message is printed. The remaining conditions are skipped.

Note that the message `15 is divisible by 5` is not printed because the condition `a_number % 5 == 0` isn't evaluated, since the previous condition `a_number % 3 == 0` evaluates to `True`. This is the key difference between using a chain of `if`, `elif`, `elif`... statements vs. a chain of `if` statements, where each condition is evaluated independently.

### Using `if`, `elif`, and `else` together

You can also include an `else` statement at the end of a chain of `if`, `elif`... statements. This code within the `else` block is evaluated when none of the conditions hold true.

In [11]:
a_number = 49

In [12]:
if a_number % 2 == 0:
    print('{} is divisible by 2'.format(a_number))
elif a_number % 3 == 0:
    print('{} is divisible by 3'.format(a_number))
elif a_number % 5 == 0:
    print('{} is divisible by 5'.format(a_number))
else:
    print('All checks failed!')
    print('{} is not divisible by 2, 3 or 5'.format(a_number))

All checks failed!
49 is not divisible by 2, 3 or 5

Conditions can also be combined using the logical operators `and`, `or` and `not`. Logical operators are explained in detail in the [first tutorial](https://jovian.ml/aakashns/first-steps-with-python/v/4#C49).

In [ ]:
a_number = 12

In [ ]:
if a_number % 3 == 0 and a_number % 5 == 0:
    print("The number {} is divisible by 3 and 5".format(a_number))
elif not a_number % 5 == 0:
    print("The number {} is not divisible by 5".format(a_number))

The number 12 is not divisible by 5

### Nested conditional statements

The code inside an `if` block can also include an `if` statement inside it. This pattern is called `nesting` and is used to check for another condition after a particular condition holds true.

In [ ]:
a_number = 15

In [13]:
if a_number % 2 == 0:
    print("{} is even".format(a_number))
    if a_number % 3 == 0:
        print("{} is also divisible by 3".format(a_number))
    else:
        print("{} is not divisible by 3".format(a_number))
else:
    print("{} is odd".format(a_number))
    if a_number % 5 == 0:
        print("{} is also divisible by 5".format(a_number))
    else:
        print("{} is not divisible by 5".format(a_number))

49 is odd
49 is not divisible by 5

## Iteration with `while` loops

`while` loops have the following syntax:

```
while condition:
    statement(s)
```

Statements in the code block under `while` are executed repeatedly as long as the `condition` evaluates to `True`.

In [15]:
result = 1
i = 1

while i <= 5:
    result = result * i
    i += 1

print('The factorial of 5 is: {}'.format(result))

The factorial of 5 is: 120

Here's another example that uses two `while` loops to create an interesting pattern.

In [ ]:
line = '*'
max_length = 10

while len(line) < max_length:
    print(line)
    line += "*"

while len(line) > 0:
    print(line)
    line = line[:-1]

*
**
***
****
*****
******
*******
********
*********
**********
*********
********
*******
******
*****
****
***
**
*

### Infinite Loops

Suppose the condition in a `while` loop always holds true. In that case, Python repeatedly executes the code within the loop forever, and the execution of the code never completes. This situation is called an infinite loop. It generally indicates that you've made a mistake in your code. For example, you may have provided the wrong condition or forgotten to update a variable within the loop, eventually falsifying the condition.

If your code is *stuck* in an infinite loop during execution, just press the "Stop" button on the toolbar (next to "Run") or select "Kernel > Interrupt" from the menu bar. This will *interrupt* the execution of the code. The following two cells both lead to infinite loops and need to be interrupted.

In [16]:
# INFINITE LOOP - INTERRUPT THIS CELL

result = 1
i = 1

while i <= 100:
    result = result * i
    # forgot to increment i

KeyboardInterrupt:

In [ ]:
# INFINITE LOOP - INTERRUPT THIS CELL

result = 1
i = 1

while i > 0 : # wrong condition
    result *= i
    i += 1

KeyboardInterrupt:

### `break` and `continue` statements

You can use the `break` statement within the loop's body to immediately stop the execution and *break* out of the loop (even if the condition provided to `while` still holds true).

In [ ]:
i = 1
result = 1

while i <= 100:
    result *= i
    if i == 42:
        print('Magic number 42 reached! Stopping execution..')
        break
    i += 1

print('i:', i)
print('result:', result)

Magic number 42 reached! Stopping execution..
i: 42
result: 1405006117752879898543142606244511569936384000000000

Sometimes you may not want to end the loop entirely, but simply skip the remaining statements in the loop and *continue* to the next loop. You can do this using the `continue` statement.

In [ ]:
i = 1
result = 1

while i < 20:
    i += 1
    if i % 2 == 0:
        print('Skipping {}'.format(i))
        continue
    print('Multiplying with {}'.format(i))
    result = result * i

print('i:', i)
print('result:', result)

Skipping 2
Multiplying with 3
Skipping 4
Multiplying with 5
Skipping 6
Multiplying with 7
Skipping 8
Multiplying with 9
Skipping 10
Multiplying with 11
Skipping 12
Multiplying with 13
Skipping 14
Multiplying with 15
Skipping 16
Multiplying with 17
Skipping 18
Multiplying with 19
Skipping 20
i: 20
result: 654729075

## Iteration with `for` loops

A `for` loop is used for iterating or looping over sequences, i.e., lists, tuples, dictionaries, strings, and *ranges*. For loops have the following syntax:

```
for value in sequence:
    statement(s)
```

The statements within the loop are executed once for each element in `sequence`. Here's an example that prints all the element of a list.

In [20]:
days = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday']

for x in days:
    print(x)

Monday
Tuesday
Wednesday
Thursday
Friday

Let's try using `for` loops with some other data types.

In [21]:
# Looping over a string
for char in 'Monday':
    print(char)

M
o
n
d
a
y

In [22]:
# Looping over a tuple
for fruit in ('Apple', 'Banana', 'Guava'):
    print("Here's a fruit:", fruit)

Here's a fruit: Apple
Here's a fruit: Banana
Here's a fruit: Guava

In [24]:
# Looping over a dictionary
person = {
    'name': 'John Doe',
    'gender': 'Male',
    'age': 32,
    'married': True
}

for a in person:
    print("Key:", a, ",", "Value:", person[a])

Key: name , Value: John Doe
Key: gender , Value: Male
Key: age , Value: 32
Key: married , Value: True

### Iterating using `range` and `enumerate`

The `range` function is used to create a sequence of numbers that can be iterated over using a `for` loop. It can be used in 3 ways:

* `range(n)` - Creates a sequence of numbers from `0` to `n-1`
* `range(a, b)` - Creates a sequence of numbers from `a` to `b-1`
* `range(a, b, step)` - Creates a sequence of numbers from `a` to `b-1` with increments of `step`

Let's try it out.

In [25]:
for i in range(7):
    print(i)

0
1
2
3
4
5
6

In [ ]:
for i in range(3, 10):
    print(i)

3
4
5
6
7
8
9

In [ ]:
for i in range(3, 14, 4):
    print(i)

3
7
11

Ranges are used for iterating over lists when you need to track the index of elements while iterating.

In [ ]:
a_list = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday']

for i in range(len(a_list)):
    print('The value at position {} is {}.'.format(i, a_list[i]))

The value at position 0 is Monday.
The value at position 1 is Tuesday.
The value at position 2 is Wednesday.
The value at position 3 is Thursday.
The value at position 4 is Friday.

### Nested `for` and `while` loops

Similar to conditional statements, loops can be nested inside other loops. This is useful for looping lists of lists, dictionaries etc.

In [ ]:
persons = [{'name': 'John', 'gender': 'Male'}, {'name': 'Jane', 'gender': 'Female'}]

for person in persons:
    for key in person:
        print(key, ":", person[key])
    print(" ")

name : John
gender : Male

name : Jane
gender : Female